//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RunningCompetitions.ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sportsman
    {
        public int ID_sportsman { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Year_birth { get; set; }
        public Nullable<int> Cost { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Id_title { get; set; }
        public Nullable<int> ID_command { get; set; }
        public string image { get; set; }
    
        public virtual Command Command { get; set; }
        public virtual Title Title { get; set; }
    }
}
